//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLCafe.BSLAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIMON
    {
        public LOAIMON()
        {
            this.THUCDONs = new HashSet<THUCDON>();
        }
    
        public string MALOAIMON { get; set; }
        public string TENLOAIMON { get; set; }
    
        public virtual ICollection<THUCDON> THUCDONs { get; set; }
    }
}
