//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLCafe.BSLAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENLIEU
    {
        public NGUYENLIEU()
        {
            this.CONGTHUCs = new HashSet<CONGTHUC>();
        }
    
        public string MANGUYENLIEU { get; set; }
        public string TENNGUYENLIEU { get; set; }
    
        public virtual ICollection<CONGTHUC> CONGTHUCs { get; set; }
    }
}
