//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLCafe.BSLAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU
    {
        public PHIEU()
        {
            this.CHITIETPHIEUx = new HashSet<CHITIETPHIEU>();
        }
    
        public string MAPHIEU { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
        public string MABAN { get; set; }
        public string MANHANVIEN { get; set; }
        public Nullable<int> THANHTIEN { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual ICollection<CHITIETPHIEU> CHITIETPHIEUx { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
