//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQLCafe.BSLAYER
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUCDON
    {
        public THUCDON()
        {
            this.CHITIETPHIEUx = new HashSet<CHITIETPHIEU>();
            this.CONGTHUCs = new HashSet<CONGTHUC>();
        }
    
        public string MAMON { get; set; }
        public string TENMON { get; set; }
        public string DVT { get; set; }
        public Nullable<int> DONGIA { get; set; }
        public string MALOAIMON { get; set; }
        public string HINHANH { get; set; }
    
        public virtual ICollection<CHITIETPHIEU> CHITIETPHIEUx { get; set; }
        public virtual ICollection<CONGTHUC> CONGTHUCs { get; set; }
        public virtual LOAIMON LOAIMON { get; set; }
    }
}
